# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib_series = [1, 2]
max_number = 4000000
x = 0

until x >= max_number do
  x = (fib_series[ fib_series.length - 1 ]) + (fib_series[ fib_series.length - 2 ])
  if x < (max_number + 1)
    fib_series.push(x)

  end
end
# puts fib_series
answer = fib_series.select{ |x| x.even?}.sum
puts answer
